tick: 10 #死亡処理のスパン(単位:tick)

fov: 70 #FOV(単位:度)
aspectRatioWide: 16 #アスペクト比 (横)
aspectRatioHeight: 9 #アスペクト比 (縦)
farClipDistance: 50 #ファークリップまでの距離

grimReaperNum: 1
grimReaperUpdateTick: 600 #(単位:tick)
